#!/usr/bin/env python3
"""Render PGHero's multi-database config from the live Komodo fleet.

PGHero needs a static `databases:` map, but the fleet is discovered dynamically. This script
reuses the provisioning service's Prometheus http_sd endpoint (which already derives host + mesh
IP from the Komodo server list) to enumerate every app host, then connects to each host's Postgres
as the read-only `pghero` role and lists the databases to analyse (default pattern `gims_%`).

Output: /config/pghero.yml with one entry per (host, database). Historical query/space stats are
stored by PGHero in its own DATABASE_URL (the manager-owned pghero-postgres), so the monitored app
databases only ever need read-only (pg_monitor) access.

Runs once at stack start (like alertmanager-init) and is re-runnable by the capture timer when the
fleet changes. Best-effort: unreachable hosts are skipped, never fatal — PGHero still boots with
whatever databases were reachable (or an empty map).
"""
import json
import os
import subprocess
import sys
import urllib.request

SD_URL = os.environ.get("SD_URL", "http://provisioning:8000/sd/gims/postgresql")
DB_USER = os.environ.get("PGHERO_DB_USER", "monitor")
DB_PASSWORD = os.environ.get("PGHERO_DB_PASSWORD", "")
DB_PATTERN = os.environ.get("PGHERO_DB_PATTERN", "gims_%")  # LIKE pattern for target databases
BOOTSTRAP_DB = os.environ.get("PGHERO_BOOTSTRAP_DB", "postgres")  # db used only to enumerate
OUT_PATH = os.environ.get("PGHERO_CONFIG_OUT", "/config/pghero.yml")
CONNECT_TIMEOUT = os.environ.get("PGHERO_CONNECT_TIMEOUT", "5")


def fetch_hosts():
    """Return [(host_name, mesh_ip), ...] from the provisioning http_sd endpoint."""
    try:
        with urllib.request.urlopen(SD_URL, timeout=10) as r:
            groups = json.loads(r.read())
    except Exception as e:  # noqa: BLE001
        print(f"[pghero-init] could not reach {SD_URL}: {e}", file=sys.stderr)
        return []
    hosts = []
    for g in groups or []:
        host = (g.get("labels") or {}).get("host", "")
        for target in g.get("targets") or []:
            ip = target.rsplit(":", 1)[0]
            if ip:
                hosts.append((host or ip, ip))
    return hosts


def list_databases(ip):
    """Enumerate target databases on a host via psql, or [] if unreachable."""
    env = dict(os.environ, PGPASSWORD=DB_PASSWORD, PGCONNECT_TIMEOUT=CONNECT_TIMEOUT)
    sql = (
        "SELECT datname FROM pg_database "
        "WHERE datallowconn AND NOT datistemplate AND datname LIKE %(p)s "
        "ORDER BY datname"
    )
    # -v binding isn't available for LIKE params via psql easily; inline the pattern safely.
    sql = sql.replace("%(p)s", "'" + DB_PATTERN.replace("'", "''") + "'")
    cmd = [
        "psql",
        "-h", ip, "-p", "5432", "-U", DB_USER, "-d", BOOTSTRAP_DB,
        "-Atqc", sql,
    ]
    try:
        out = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=20)
    except Exception as e:  # noqa: BLE001
        print(f"[pghero-init] {ip}: psql failed to run: {e}", file=sys.stderr)
        return []
    if out.returncode != 0:
        print(f"[pghero-init] {ip}: enumeration failed: {out.stderr.strip()}", file=sys.stderr)
        return []
    return [line.strip() for line in out.stdout.splitlines() if line.strip()]


def yaml_escape(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    hosts = fetch_hosts()
    entries = []  # (key, url)
    for host, ip in hosts:
        dbs = list_databases(ip)
        if not dbs:
            print(f"[pghero-init] {host} ({ip}): no target databases / unreachable — skipped")
            continue
        for db in dbs:
            key = f"{host}__{db}"
            # The written URL carries NO secret: PGHero renders pghero.yml through ERB, so the
            # password is pulled from the pghero container's own env at load time. Keeps this file
            # (and git) free of credentials.
            url = (
                f"postgres://{DB_USER}:<%= ENV['PGHERO_DB_PASSWORD'] %>@{ip}:5432/{db}"
                f"?connect_timeout={CONNECT_TIMEOUT}"
            )
            entries.append((key, url))
            print(f"[pghero-init] + {key} -> {ip}:5432/{db}")

    lines = [
        "# GENERATED by docker/pghero/generate-config.py — do not edit by hand.",
        "# One entry per (host, database), discovered from the Komodo fleet. Historical stats are",
        "# stored in PGHero's own DATABASE_URL (pghero-postgres), so these connections stay read-only.",
        "# Rendered as ERB by PGHero: the password comes from ENV['PGHERO_DB_PASSWORD'] at load time,",
        "# so no credential is written here.",
        "databases:",
    ]
    if not entries:
        lines.append("  {}  # no reachable databases at generation time")
    for key, url in entries:
        lines.append(f"  {yaml_escape(key)}:")
        lines.append(f"    url: {yaml_escape(url)}")
        lines.append("    capture_query_stats: true")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[pghero-init] wrote {len(entries)} database(s) to {OUT_PATH}")


if __name__ == "__main__":
    main()
